In [3]:
import numpy as np

In [4]:
# Tạo mảng có độ dài 10 với các giá trị ban đầu là số 0:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# Tạo mảng hai chiểu kích thước 3x5 với mỗi phần tử là số 1:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Tạo mảng hai chiều kích thước 3x5 với các giá trị là 3.14:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
# Tạo mảng một chiều các giá trị là 1 dãy bắt đầu từ 0  18, bước nhảy là 2:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.empty(3)

array([ 1.60218491e-306,  1.06860806e-311, -0.00000000e+000])

In [10]:
a = np.array([1, 2, 3])

In [11]:
np.add.reduce(a)

6

In [12]:
np.add.accumulate(a)

array([1, 3, 6], dtype=int32)