In [3]:
import numpy as np

In [4]:
# Xay dung ham
def nhap_ma_tran_2_chieu(hang, cot):
    """
    ham nhap vao ma tran va tra ve list da chieu
    """
    ma_tran = []
    for i in range(hang):
        a = []
        for j in range(cot):
            print("\tPhan tu thu [{0}][{1}] la:".format(i+1, j+1), end=" ")
            a.append(int(input()))
        ma_tran.append(a)
    return ma_tran

In [5]:
# Chuong trinh chinh
hang = int(input("Nhap vao so hang: "))
cot = int(input("Nhap vao so cot: "))
print("Nhap vao ma tran A:")
matrix_a = np.array(nhap_ma_tran_2_chieu(hang, cot))
print("Nhap vao ma tran B:")
matrix_b = np.array(nhap_ma_tran_2_chieu(hang, cot))

# Tinh tong hai ma tran
matrix_c = np.add(matrix_a, matrix_b)

# hien thi
print("Ma tran A vua nhap la:")
print(matrix_a)
print("Ma tran B vua nhap la:")
print(matrix_b)
print("Ma tran C la:")
print(matrix_c)

Nhap vao so hang: 2
Nhap vao so cot: 3
Nhap vao ma tran A:
	Phan tu thu [1][1] la: 1
	Phan tu thu [1][2] la: 2
	Phan tu thu [1][3] la: 3
	Phan tu thu [2][1] la: 4
	Phan tu thu [2][2] la: 5
	Phan tu thu [2][3] la: 2
Nhap vao ma tran B:
	Phan tu thu [1][1] la: 1
	Phan tu thu [1][2] la: 2
	Phan tu thu [1][3] la: 1
	Phan tu thu [2][1] la: 2
	Phan tu thu [2][2] la: 2
	Phan tu thu [2][3] la: 1
Ma tran A vua nhap la:
[[1 2 3]
 [4 5 2]]
Ma tran B vua nhap la:
[[1 2 1]
 [2 2 1]]
Ma tran C la:
[[2 4 4]
 [6 7 3]]
