# The Basics of NumPy Arrays

Chúng tôi sẽ đề cập đến một số loại thao tác mảng cơ bản ở đây:

Các thuộc tính của mảng: Xác định kích thước, hình dạng, mức tiêu thụ bộ nhớ và kiểu dữ liệu của mảng

* Lập chỉ mục mảng: Lấy và đặt giá trị của các phần tử mảng riêng lẻ

* Cắt mảng: Lấy và thiết lập các mảng con nhỏ hơn trong một mảng lớn hơn

* Định hình lại mảng: Thay đổi hình dạng của một mảng nhất định

* Nối và tách mảng: Kết hợp nhiều mảng thành một và chia một mảng thành nhiều

### NumPy Array Attributes

 Xác định ba mảng ngẫu nhiên, một mảng một chiều, hai chiều và ba chiều.

In [9]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=(6)) # One-dimensional array (6 phần tử)
x2 = np.random.randint(10, size=(3,4)) # Two-dimensional array (3 dòng; 2 cột)
x3 = np.random.randint(10, size=(3,4,5)) # Three-dimensional array

* Mỗi mảng có các thuộc tính ndim (số thứ nguyên), shape (kích thước của mỗi thứ nguyên) và size (tổng kích thước của mảng):

In [16]:
print("x3 ndim: ", x3.ndim) # xđ mảng có bao nhiêu chiều
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size) # số phần tử có trong mảng

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [18]:
print("dtype:", x3.dtype)

dtype: int32


* Các thuộc tính khác bao gồm kích thước mục, liệt kê kích thước (tính bằng byte) của mỗi phần tử mảng và nbyte, liệt kê tổng kích thước (tính bằng byte) của mảng:

In [20]:
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize:  4 bytes
nbytes: 240 bytes


* nbyte = itemsize*size.

### Array Indexing: Accessing Single Elements

In [21]:
x1

array([5, 0, 3, 3, 7, 9])

In [24]:
x1[4]

7

* Để lập chỉ mục từ cuối mảng, bạn có thể sử dụng các chỉ số phủ định:

In [23]:
x1[-1]

9

* Trong một mảng nhiều chiều, các mục có thể được truy cập bằng cách sử dụng nhiều chỉ số được phân tách bằng dấu phẩy:

In [25]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [27]:
x2[0,1]

5

In [28]:
x2[2, -1]

7

* Giá trị cũng có thể được sửa đổi bằng cách sử dụng bất kỳ ký hiệu chỉ mục nào ở trên:

In [29]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

* Hãy nhớ rằng, không giống như danh sách Python, mảng NumPy có một kiểu cố định. Điều này có nghĩa là, ví dụ, nếu bạn cố gắng chèn một giá trị dấu phẩy động vào một mảng số nguyên, giá trị sẽ bị cắt bớt một cách âm thầm. Đừng để bị bắt không biết bởi hành vi này!

In [30]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

### Array Slicing: Accessing Subarrays

x[start:stop:step]

* Nếu bất kỳ giá trị nào trong số này không được xác định, chúng được đặt mặc định thành các giá trị start = 0, stop = size của thứ nguyên, bước = 1. Chúng ta sẽ xem xét việc truy cập các mảng con trong một chiều và nhiều chiều.

#### One-dimensional subarrays

In [33]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [36]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [37]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [41]:
x[::2]  # every other element (bước nhảy)

array([0, 2, 4, 6, 8])

In [42]:
x[1::2]  # (bắt đầu từ index = 1 bước nhảy 2)

array([1, 3, 5, 7, 9])

* Một trường hợp có thể gây nhầm lẫn là khi giá trị bước là âm. Trong trường hợp này, các giá trị mặc định cho bắt đầu và dừng được hoán đổi. Điều này trở thành một cách thuận tiện để đảo ngược một mảng

In [43]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [44]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

#### Multi-dimensional subarrays

In [45]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [46]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [47]:
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [48]:
x2[1::3, ::2]

array([[7, 8]])

* Cuối cùng, các kích thước của mảng con thậm chí có thể được đảo ngược với nhau:

In [49]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accessing array rows and columns

* Một thói quen thường cần là truy cập các hàng hoặc cột đơn lẻ của một mảng. Điều này có thể được thực hiện bằng cách kết hợp lập chỉ mục và cắt, sử dụng một lát trống được đánh dấu bằng dấu hai chấm (:):

In [50]:
print(x2[:, 0])  # cột đầu tiên của x2

[12  7  1]


In [51]:
print(x2[0, :]) # dòng đầu tiên của x2

[12  5  2  4]


* Trong trường hợp truy cập hàng, có thể bỏ qua lát trống để có cú pháp gọn gàng hơn:

In [53]:
print(x2[0])

[12  5  2  4]


#### Subarrays as no-copy views

* Một điều quan trọng và cực kỳ hữu ích - cần biết về các lát mảng là chúng trả về các dạng xem thay vì bản sao của dữ liệu mảng. Đây là một khu vực trong đó việc cắt mảng NumPy khác với cách cắt danh sách trong Python: trong danh sách, các lát cắt sẽ là bản sao. Hãy xem xét mảng hai chiều của chúng ta từ trước:

In [55]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


* Hãy trích xuất một mảng con 2 × 2 từ mảng này:

In [59]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


* Bây giờ nếu chúng ta sửa đổi mảng con này, chúng ta sẽ thấy rằng mảng ban đầu đã bị thay đổi! Quan sát:

In [60]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [61]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


* Hành vi mặc định này thực sự khá hữu ích: có nghĩa là khi chúng ta làm việc với các bộ dữ liệu lớn, chúng ta có thể truy cập và xử lý các phần của các bộ dữ liệu này mà không cần sao chép bộ đệm dữ liệu bên dưới.

#### Creating copies of arrays

* Mặc dù có các tính năng tuyệt vời của chế độ xem mảng, nhưng thay vào đó, việc sao chép dữ liệu một cách rõ ràng trong một mảng hoặc một mảng con sẽ rất hữu ích. Điều này có thể được thực hiện dễ dàng nhất với phương thức copy ():

In [62]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


* Nếu bây giờ chúng ta sửa đổi mảng con này, mảng ban đầu sẽ không bị thay đổi:

In [63]:
x2_sub_copy[0,0] = 11
print(x2_sub_copy)

[[11  5]
 [ 7  6]]


In [64]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


#### Reshaping of Arrays

* Một loại hoạt động hữu ích khác là định hình lại các mảng. Cách linh hoạt nhất để làm điều này là với phương pháp định hình lại. Ví dụ: nếu bạn muốn đặt các số từ 1 đến 9 trong lưới 3 × 3, bạn có thể thực hiện như sau:

In [66]:
grid = np.arange(1, 10).reshape(3, 3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

* Lưu ý rằng để điều này hoạt động, kích thước của mảng ban đầu phải khớp với kích thước của mảng được định hình lại. Nếu có thể, phương thức định hình lại sẽ sử dụng chế độ xem không sao chép của mảng ban đầu, nhưng với các bộ đệm bộ nhớ không liền kề, điều này không phải lúc nào cũng đúng.

* Một kiểu định hình lại phổ biến khác là chuyển đổi mảng một chiều thành ma trận hàng hoặc cột hai chiều. Điều này có thể được thực hiện bằng phương pháp định hình lại hoặc dễ dàng thực hiện hơn bằng cách sử dụng từ khóa newaxis trong một thao tác lát:

In [116]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [117]:
t = x.reshape((1, 3)).copy()

In [118]:
t

array([[1, 2, 3]])

In [68]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [69]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [72]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### Nối và tách mảng

#### Concatenation of arrays (Nối các mảng)

* Việc nối hoặc nối hai mảng trong NumPy chủ yếu được thực hiện bằng cách sử dụng các quy trình np.concatenate, np.vstack và np.hstack. np.concatenate lấy một tuple hoặc danh sách các mảng làm đối số đầu tiên của nó, như chúng ta có thể thấy ở đây:

In [74]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate((x, y))

array([1, 2, 3, 3, 2, 1])

In [75]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [76]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


* Dùng cho mảng 2 chiều

In [77]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [78]:
# nối dọc theo trục đầu tiên
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [115]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15]])

* Để làm việc với các mảng có kích thước hỗn hợp, có thể rõ ràng hơn khi sử dụng hàm np.vstack (ngăn xếp dọc) và np.hstack (ngăn xếp ngang):

In [80]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

In [85]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [86]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

* Tương tự, np.dstack sẽ xếp các mảng dọc theo trục thứ ba.

In [98]:
x_x3 = np.array([[[1, 2, 3]]])
grid_x3 = np.array([[[1, 2, 3],
                   [2, 3, 4],
                   [4, 3, 2]]])
grid_x3

array([[[1, 2, 3],
        [2, 3, 4],
        [4, 3, 2]]])

In [99]:
np.hstack([grid_x3, x_x3])

array([[[1, 2, 3],
        [2, 3, 4],
        [4, 3, 2],
        [1, 2, 3]]])

In [107]:
y_x3 = np.array([[[1],
                 [2],
                 [99]]])
# np.vstack([y_x3, grid_x3])

#### Splitting of arrays

* Ngược lại với nối là tách, được thực hiện bởi các hàm np.split, np.hsplit và np.vsplit. Đối với mỗi điều này, chúng ta có thể chuyển một danh sách các chỉ số đưa ra các điểm phân tách:

In [108]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


* Lưu ý rằng N điểm phân tách, dẫn đến N + 1 mảng con. Các chức năng liên quan np.hsplit và np.vsplit tương tự:

In [109]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
upper, lower = np.vsplit(grid, [2])
print(upper)

[[0 1 2 3]
 [4 5 6 7]]


In [112]:
print(lower)

[[ 8  9 10 11]
 [12 13 14 15]]


In [113]:
left, right = np.hsplit(grid, [2])
print(left)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [114]:
print(right)

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
